export const cardsData = [
  {
    id: 1,
    imgSrc: "moon.png",
    title: "GalactChat Messaging App (MERN)",
    subTitle: "mehi meh",
    live: "",
    github: "",
    moreInfo: "2002 may 5th",
    bullets: [
      "Full-stack chat built on React, Redux, Websockets, Node.js, and MongoDB. Socket.io for real-time communication",
      "AI image generator DALL.E for easier and fun registration",
      "Server-side authentication through cookies and JWT",
      "Mongo Atlas and Cloudinary for scalability and cloud storage",
    ],
  },
  {
    id: 2,
    imgSrc: "https://picsum.photos/400/200",
    title: "Algorithm Visualizer (JavaScript)",
    subTitle: "mehi meh",
    live: "",
    github: "",
    moreInfo: "2002 may 5th",
    bullets: [
      "7 path finding algorithms. Minimum spanning trees. Topological sorting. Sudoku solver. Chess AI thinking visualization.",
      "Bullet 2",
      "Bullet 3",
    ],
  },
  {
    id: 3,
    imgSrc: "https://picsum.photos/400/200",
    title: "Social Network and E-commerce App",
    subTitle: "mehi meh",
    live: "",
    github: "",
    moreInfo: "2002 may 5th",
    bullets: [
      "Full-stack social network and e-commerce website built on Django, Python, JavaScript with authentication, CRUD, mai",
      "AWS S3 and Postgresql used for cloud storage and availability",
      "Bullet 3",
    ],
  },
  {
    id: 4,
    imgSrc: "https://picsum.photos/400/200",
    title: "Fuel Combustion Data Analysis",
    subTitle: "mehi meh",
    live: "",
    github: "",
    moreInfo: "2002 may 5th",
    bullets: [
      "Total of 1 billion grid points were used for 3D computation of jet flames leading to 5.4 million CPU-hours (3000 human hours) of simulation running on 2000 computer cores simultaneously using parallel programming in C++ and Fortran",
      "Various post-processing using Python and Matplotlib.",
      "Thousands of contributions to the source code for running and post analysing flames (not public but can be demonstrated)",
    ],
  },
  {
    id: 5,
    imgSrc: "https://picsum.photos/400/200",
    title: "Card 5",
    subTitle: "mehi meh",
    live: "",
    github: "",
    moreInfo: "2002 may 5th",
    bullets: ["Bullet 1", "Bullet 2", "Bullet 3"],
  },
  {
    id: 6,
    imgSrc: "https://picsum.photos/400/200",
    title: "Card 6",
    subTitle: "mehi meh",
    live: "",
    github: "",
    moreInfo: "2002 may 5th",
    bullets: ["Bullet 1", "Bullet 2", "Bullet 3"],
  },
];
