export const cardsData = [
  {
    id: 1,
    imgSrc: "chatmain.png",
    title: "GalactChat Messaging App (MERN)",
    subTitle: "React; Redux; Node.js; Socket.io; Cloudinary; Axios; Express; Mongoose; Openai;",
    live: "https://galactchat.netlify.app/",
    github: "https://github.com/samyarsworld/galactchat-chat-app-backend",
    moreInfo: "2023 March 11th",
    bullets: [
      "Full-stack chat built on React, Redux, Websockets, Node.js, and MongoDB. Socket.io for real-time communication",
      "AI image generator DALL.E for easier and fun registration",
      "Server-side authentication through cookies and JWT",
      "Mongo Atlas and Cloudinary used for scalability and cloud storage",
    ],
  },
  {
    id: 2,
    imgSrc: "algomain.png",
    title: "Algorithm Visualizer (JavaScript)",
    subTitle: "Javascript; Bootstrap; Path Finding Algorithms; Toast;",
    live: "https://samyarsworld.github.io/",
    github: "https://github.com/samyarsworld/samyarsworld.github.io",
    moreInfo: "2023 March 30th",
    bullets: [
      "7 path finding algorithms visualizers",
      "Minimum spanning trees visualizer",
      "Topological sorting visualizer",
    ],
  },
  {
    id: 3,
    imgSrc: "networkmain.png",
    title: "Social Network and E-commerce App",
    subTitle: "Django; Python; boto3; AWS S3; AWS RDS; Postgres; Openai;",
    live: "https://galactus.onrender.com/",
    github: "https://github.com/samyarsworld/social-network",
    moreInfo: "2022 Dec 4th",
    bullets: [
      "Full-stack social network and e-commerce website built on Django, Python, JavaScript with authentication, CRUD, and AI",
      "AWS S3 and Postgresql (AWS RDS) used for cloud storage and availability",
      "Ability to follow friends, attend bidding for auctions, comments, post ideas, and create and buy listing",
    ],
  },
  {
    id: 4,
    imgSrc: "paperfuel.png",
    title: "Fuel Combustion Data Analysis",
    subTitle: "Fortran; C++; Python; Matplotlib; Numpy; Panda; Linux; Latex;",
    live: "https://www.sciencedirect.com/science/article/pii/S0010218022001523",
    github: "",
    moreInfo: "2022 March 22th",
    bullets: [
      "Total of 1 billion grid points were used for 3D computation of jet flames leading to 5.4 million CPU-hours (3000 human hours) of simulation running on 2000 computer cores simultaneously using parallel programming in C++ and Fortran",
      "Various post-processing using Python and Matplotlib",
      "Thousands of contributions to the source code for running and post analysing flames (not public but can be demonstrated)",
    ],
  },
  {
    id: 5,
    imgSrc: "chessmain.png",
    title: "Chess AI Engine",
    subTitle: "Python; Pygame; Minimax;",
    live: "https://github.com/samyarsworld/chess-ai",
    github: "https://github.com/samyarsworld/chess-ai",
    moreInfo: "2023 April 28th",
    bullets: ["Chess game built using Python and Pygame", "Added multiple algorithms to reduce computation time for AI generated moves reducing runtime by 1000 folds from a normal minimax algorithm", "Storage and hashmap techniques used to reduce the UI update times by 90%"],
  }
];
